import PyInstaller.__main__

PyInstaller.__main__.run([
    'main.py',
    '--onefile',
    '--noconsole',
    '--name', 'CK3_AI_Assistant',
    '--log-level=DEBUG',
    '--exclude-module', 'PyQt6',
    '--exclude-module', 'matplotlib_inline',
    '--exclude-module', 'IPython',
    '--exclude-module', 'jupyter',
    '--exclude-module', 'nbconvert',
    '--exclude-module', 'nbformat',
    '--exclude-module', 'notebook',
    '--hidden-import=queue',
    '--hidden-import=pyaudio',
    '--hidden-import=pygame',
    '--hidden-import=PIL',
    '--hidden-import=requests',
    '--hidden-import=wave',
    '--hidden-import=numpy',
    '--hidden-import=tkinter',
    '--hidden-import=asyncio',
    '--hidden-import=io',
    '--hidden-import=threading',
    '--hidden-import=logging',
    '--hidden-import=argparse',
    '--clean'
])
